
- name: "create .kube/observability/opentelemetry directory"
  file:
    path: ".kube/observability/prometheus"
    state: directory


- name: Copy opentelemetry helm chart (takes some time)
  ansible.posix.synchronize:
    src: observability/opentelemetry
    dest: "{{ansible_env.HOME}}/.kube/observability/opentelemetry-operator_chart"

- name: Generate values template file for prometheus
  template: 
    src: "{{ item }}.j2"
    dest: ".kube/observability/{{ item }}"
  with_items:
    - prometheus/prometheus_operator_bundle.yaml
    - prometheus/test_node_exporter.yml
    - prometheus/test_prometheus.yml

- name: Deploy prometheus
  shell: |
    kubectl --kubeconfig=.kube/config \
        apply -f .kube/prometheus/{{ item }} --validate='strict' && sleep 10
  register: create_result
  until: create_result.rc == 0
  retries: 6
  delay: 60
  ignore_errors: true
  with_items:
    - prometheus/prometheus_operator_bundle.yaml
    - prometheus/test_node_exporter.yml
    - prometheus/test_prometheus.yml
  notify: "restart not ready kube-system pods" #look a handler/main.yml


