- name: Purge NTP package
  apt:
    name: ntp
    state: absent
    purge: true
  become: true

- name: systemd-timesyncd package
  apt:
    name: systemd-timesyncd
    state: present
  become: true
  when: ansible_distribution == "Debian"

- name: Push timesyncd conf file
  template:
    src: "timesyncd.conf.j2"
    dest: "/etc/systemd/timesyncd.conf"
    owner: "{{ ansible_become_user }}"
    group: "{{ ansible_become_user }}"
  become: true

- name: Start systemd-timesyncd service
  systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
  become: true

- name: Enable timedatectl to synchro on NTP
  command: timedatectl set-ntp true
  become: yes




  