
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - snmpd
  become: true

- name: Copy snmpd conf file
  copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  become: true
  notify:
    - Restart snmpd
