---
# pour deploiemenet de pixie il faut enlever TOUS les svc.cluster.local du fichier yaml/cloud.yaml
# kube
# Ansible 
guest_user_pass: generic
guest_root_pass: root
ansible_python_interpreter: /usr/bin/python3
ansible_user: user
ansible_become_user: root
ansible_password: "{{ guest_user_pass }}"
ansible_become_password: "{{ guest_root_pass }}"
ansible_become_method: su
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Common
ntp_server_ip: '192.168.17.4'
offline_dir: /srv/k8s_offline

# Kubernetes
cluster_name: cluster.local
container_runtime: containerd
kube_version: 1.32.0-00
controlPlaneEndpoint: kmsr01.johto.tdmc:6443
vault_rootpki_endpoint: vault.dev.lan
vault_cloud_tmp_tkn: hvs.vomyc81HjZTQ5aaYYJniLkL1
vault_autounseal_token: hvs.CAESIPCbmfE58rGnnun36UsMM2DQff-A9vNzRKNPDKNq-kwiGh4KHGh2cy41NU1wQ1o3b2JQZW1SMXFON1pESlNSbjk
registry_k8s: 'rgy01.johto.tdmc'
pause_img_version: 3.9
cluster_token: abcdef.0123456789abcdef
certificateKey: 76e20fb6cbfeef9fbe0931bfe851281fb482b23efaa98e856aba4877574df077
repo_k8s_kubeadm: http://rpo01.kalos.tdmc:8080/kubeadm/  kubernetes-xenial main
#repo_k8s_crio_main: http://rpo01.kalos.tdmc:8080/cri-o/ .-- main
#repo_k8s_crio: http://rpo01.kalos.tdmc:8080/cri-o_1.32/ .-- main
kubeadm_gpg: repo_k8s_dev_lan.gpg
serviceSubnet: "10.10.0.0/16"
podSubnet: "10.11.0.0/16"
dnsDomain: cluster.local
cilium:
  version: "1.16.0"
  mode: default # values are ebpf or default

openebs:
  namespace: openebs
  cstor: 
    default_pool: 
      default_pool_disks: 'sde|sdf|sdg|sdh' # format : 'sdc' ou 'sdc|sdb|sda' pour le moment, que les disques des masters sont pris
      default_pool_data_type: 'stripe' #stripe or mirrored
      default_storage_class_replicacount: 2

benchmark: 
  elastic: 
    namespace: "elasticsearch"
    storage: 1600Gi #Gi mandatory, must not exceed the size of the disks set below
    disks: "sdc" #prend ce disque seulement sur les workers 
    racks:
      # on peut mettre autant de rack qu'on veut, et on peut meme changer le nom des racks (au lieu de rack1 on peut mettre autre chose), cela change seulement le label donné au noeud pour topology.kubernetes.io/zone="rack1"
      rack1: "kwkr[01-04]" # doit respecter le format de nodeset (worker[1-3,5] donne worker1,worker2,worker3,worker5)
      rack2: "kwkr[05-08]"
      rack3: "kwkr[09-10]"
  esrally: #esrally will be in the same namespace as benchmark elastic
    tracks: geonames #currently only geonames and pmc are supported

observability: 
  backend_namespace: opentelemetry
  pyroscope: 
    enable: false
  clickhouse: 
    enable: false


