apiVersion: v2
appVersion: 0.17.15
dependencies:
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 15.16.*
- condition: node-agent.enabled
  name: node-agent
  repository: https://coroot.github.io/helm-charts
  version: 0.1.39
- condition: pyroscope.enabled
  name: pyroscope
  repository: https://pyroscope-io.github.io/helm-chart
  version: 0.2.*
- condition: pyroscope-ebpf.enabled
  name: pyroscope-ebpf
  repository: https://pyroscope-io.github.io/helm-chart
  version: 0.1.*
- condition: clickhouse.enabled
  name: clickhouse
  repository: https://charts.bitnami.com/bitnami
  version: 3.1.*
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.52.*
description: A monitoring and troubleshooting tool for microservice architectures.
name: coroot
type: application
version: 0.3.8
