- name: Push containerd config file
  template:
    src: "containerd_config.toml.j2"
    dest: "/etc/containerd/config.toml"
    owner: "{{ ansible_become_user }}"
    group: "{{ ansible_become_user }}"
  become: true

- name: Restart service containerd
  systemd:
    name: containerd
    state: restarted
  become: true
