---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket=unix:///var/run/crio/crio.sock"
  become: true

- name: Load predownloaded Kubernetes images
  shell: |
    for img in {{ offline_dir }}/images/*.tar.gz; do
      crictl load "$img"
    done
  when: offline_dir is defined
  become: true

- name: Generate join token for workers
  shell: |
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH && \
    kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'][0] }}"
  become: true

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"


- name: Run kubeadm join
  shell: |
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH && \
    {{ kubeadm_join }} --cri-socket=unix:///var/run/crio/crio.sock
  become: true 

- name: Recreate kube-dns
  command: kubectl -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  ignore_errors: true

