- name: create trousseau dir
  file:
    path: ".kube/trousseau"
    state: directory 

- name: Copy trousseau files to Home directory
  copy:
    src: "{{ item }}"
    dest: ".kube/trousseau/{{ item }}"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
  with_items:
    - 'vault.{{ dnsDomain }}.crt'
    - 'vault.{{ dnsDomain }}.key'
    - 'ca-chain.crt'
    - 'serviceaccount_token.yml'
    - 'secret_test.yml'

- name: Create vault-tls secret for trousseau
  shell: |
    kubectl --kubeconfig=.kube/config -n kube-system create secret generic vault-tls \
    --from-file=vault.crt=.kube/trousseau/vault.{{ dnsDomain }}.crt \
    --from-file=vault.key=.kube/trousseau/vault.{{ dnsDomain }}.key \
    --from-file=vault.ca=.kube/trousseau/ca-chain.crt\
  ignore_errors: true

- name: Deploy troussault service accounts into cluster
  shell: |
    kubectl --kubeconfig=.kube/config \
        apply -f .kube/trousseau/{{ item }} && sleep 20
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true
  with_items:
    - serviceaccount_token.yml
    - secret_test.yml

