
- name: wait for pods to become ready
  shell: "kubectl wait pods --all --namespace kube-system --for=condition=Ready --all=true --timeout=5s 2>&1 | grep 'timed out waiting for' | awk '{print $NF}'"
  register: control_plane_pods_not_ready
  listen: "restart not ready kube-system pods"

- name: output pods that are not ready 
  debug:
    msg: "{{ control_plane_pods_not_ready.stdout_lines }}"
  listen: "restart not ready kube-system pods"

- name: kill pods that are not ready 
  shell: "kubectl delete --namespace kube-system {{ control_plane_pods_not_ready.stdout | replace('\n',' ') }}"
  when: control_plane_pods_not_ready.stdout | length >0
  listen: "restart not ready kube-system pods"

- name: wait for pods to become Initialized
  shell: "kubectl wait pods --all --namespace kube-system --for=condition=Ready --all=true --timeout=5s 2>&1 | grep 'timed out waiting for' | awk '{print $NF}'"
  register: control_plane_pods_not_ready2
  failed_when: control_plane_pods_not_ready2.stdout | length >0
  when: control_plane_pods_not_ready.stdout | length >0
  listen: "restart not ready kube-system pods"


- name: wait for observability-frontend  pods to become ready
  shell: "kubectl wait pods --all --namespace observability-frontend --for=condition=Ready --all=true --timeout=50s 2>&1 | grep 'timed out waiting for' | grep -v vault-server-test | awk '{print $NF}' && sleep 20"
  register: control_plane_pods_not_ready
  listen: "restart not ready vault pods"

- name: output observability-frontend  pods that are not ready 
  debug:
    msg: "{{ control_plane_pods_not_ready.stdout_lines }}"
  listen: "restart not ready vault pods"

- name: kill observability-frontend  pods that are not ready 
  shell: "kubectl delete --namespace observability-frontend {{ control_plane_pods_not_ready.stdout | replace('\n',' ') }}"
  when: control_plane_pods_not_ready.stdout | length >0
  listen: "restart not ready vault pods"

- name: wait for observability-frontend  pods to become ready again
  shell: "kubectl wait pods --all --namespace observability-frontend --for=condition=Ready --all=true --timeout=50s 2>&1 | grep 'timed out waiting for' | awk '{print $NF}'"
  register: control_plane_pods_not_ready2
  failed_when: control_plane_pods_not_ready2.stdout | length >0
  when: control_plane_pods_not_ready.stdout | length >0
  listen: "restart not ready vault pods"




