apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata: 
  name: test
  namespace: coroot
spec:
  env:
    - name: CLICKHOUSE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: clickhouse
          key: admin-password
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10
        timeout: 10s

    exporters:
      clickhouse:
        endpoint: clickhouse://clickhouse:9000?dial_timeout=10s&compress=lz4
        database: coroottraces
        ttl_days: 7
        username: default
        password: ${CLICKHOUSE_PASSWORD}
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        timeout: 20s
        retry_on_failure:
          enabled: true
          initial_interval: 20s
          max_interval: 60s
          max_elapsed_time: 300s
      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging,clickhouse]
        
