- name: Install a list of docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce={{ apt_docker_version_os }}
    - docker-ce-cli={{ apt_docker_version_os }}
    - containerd.io={{ apt_container_version }}
  become: true