apiVersion: v2
appVersion: 1.0.0
dependencies:
- alias: agent
  condition: agent.enabled
  name: grafana-agent
  repository: https://grafana.github.io/helm-charts
  version: '>=0.21.0'
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 4.0.12
description: "\U0001F525 horizontally-scalable, highly-available, multi-tenant continuous
  profiling aggregation system"
kubeVersion: '>=1.22'
name: pyroscope
type: application
version: 1.0.0
