{{- if and .Values.corootCE.enabled .Values.corootCE.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coroot.serviceAccountName" . }}
  labels:
    {{- include "coroot.labels" . | nindent 4 }}
  {{- with .Values.corootCE.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
