apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pyroscope-ebpf.fullname" . }}
  labels:
    {{- include "pyroscope-ebpf.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
