- name: Install base utilities for Kubernetes
  apt:
    name:
      - jq
      - curl
      - parted
  become: true

- name: Install containerd packages from offline directory
  apt:
    deb: "{{ item }}"
  loop: "{{ lookup('fileglob', offline_dir + '/containerd/packages/*.deb', wantlist=True) }}"
  become: true
  when: container_runtime == "containerd"

- name: Install Kubernetes binaries from offline archive
  copy:
    src: "{{ offline_dir }}/k8s/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: '0755'
    remote_src: yes
  loop:
    - kubeadm
    - kubelet
    - kubectl
  become: true

- name: Enable and check containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet
  become: true
  when: container_runtime == "containerd"

- name: Load pre-downloaded containerd images
  shell: "ctr -n k8s.io images import {{ item }}"
  with_fileglob:
    - "{{ offline_dir }}/containerd/images/*.tar"
  become: true
  when: container_runtime == "containerd"

# Hold containerd package version to prevent update
- dpkg_selections:
    name: containerd.io
    selection: hold
  become: true
  when: container_runtime == "containerd"
