- name: Install base utilities for Kubernetes
  apt:
    name:
      - jq
      - curl
      - parted
  become: true

- name: Install CRI-O packages from offline directory
  apt:
    deb: "{{ item }}"
  loop: "{{ lookup('fileglob', offline_dir + '/crio/packages/*.deb', wantlist=True) }}"
  become: true
  when: container_runtime == "crio"

- name: Install Kubernetes binaries from offline archive
  copy:
    src: "{{ offline_dir }}/k8s/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: '0755'
    remote_src: yes
  loop:
    - kubeadm
    - kubelet
    - kubectl
  become: true

- name: Enable and check crio service
  systemd:
    name: crio
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet
  become: true
  when: container_runtime == "crio"

- name: Load pre-downloaded CRI-O images
  shell: "crictl load {{ item }}"
  with_fileglob:
    - "{{ offline_dir }}/crio/images/*.tar"
  become: true
  when: container_runtime == "crio"

# Hold CRI-O packages version to prevent update
- dpkg_selections:
    name : "{{ item }}"
    selection: hold
  become: true
  loop:
    - cri-o
    - cri-o-runc  when: container_runtime == "crio"